models/leprechaun/hoodman.mdl
models/leprechaun/panther.mdl
models/leprechaun/panther01.mdl
models/leprechaun/panther02.mdl
models/leprechaun/pantherT.mdl
models/leprechaun/pengybot.mdl
models/leprechaun/pengycontroller.mdl
models/leprechaun/pengycontrollerT.mdl
models/leprechaun/troll-big.mdl
models/leprechaun/troll-bigT.mdl
sound/leprechaun/gman-final.wav
sound/leprechaun/gman2-final.wav
sound/leprechaun/grunt1-final.wav
sound/leprechaun/grunt2-final.wav
sound/leprechaun/grunt3-final.wav
sound/leprechaun/grunt4.wav
sound/leprechaun/hermit-final.wav
sound/leprechaun/Lep-part1.wav
sound/leprechaun/Lep-part2.wav
sound/leprechaun/Lep-part3.wav
sound/leprechaun/Lep-part4.wav
gfx/env/riverscape1bk.tga
gfx/env/riverscape1dn.tga
gfx/env/riverscape1ft.tga
gfx/env/riverscape1lf.tga
gfx/env/riverscape1rt.tga
gfx/env/riverscape1up.tga
leprechaun.wad
maps/leprechaun1.cfg
maps/leprechaun1_motd.txt
maps/leprechaun1_skl.cfg
maps/leprechaun2.cfg
maps/leprechaun2_motd.txt
maps/leprechaun3.cfg
maps/leprechaun3_motd.txt
maps/leprechaun3_skl.cfg
maps/leprechaun3-2.cfg
maps/leprechaun3-2_motd.txt
maps/leprechaun3-2_skl.cfg
maps/leprechaun1.res
maps/leprechaun2.res
maps/leprechaun3.res
maps/leprechaun3-2.res