maps/never.cfg
maps/never_skl.cfg
maps/never_motd.txt
maps/never.txt
maps/never.res

models/bmt/never/aigunner.mdl
models/bmt/never/bcontroller.mdl
models/bmt/never/bcontrollerT.mdl
models/bmt/never/islave.mdl
sound/bmt/gunner/ai_firegun.wav
sound/bmt/gunner/ai_powerup.wav
sound/bmt/never_a.wav
sound/bmt/never_destroy.wav
sound/bmt/never_escape.wav
sound/bmt/never_tragic.wav
sound/bmt/never_weird.wav
sound/bmt/stage2_1.mp3
sound/bmt/stage3_1.mp3
sound/bmt/stage4_1.mp3
