decals.wad
gfx/env/dfcliffbk.bmp
gfx/env/dfcliffbk.tga
gfx/env/dfcliffdn.bmp
gfx/env/dfcliffdn.tga
gfx/env/dfcliffft.bmp
gfx/env/dfcliffft.tga
gfx/env/dfclifflf.bmp
gfx/env/dfclifflf.tga
gfx/env/dfcliffrt.bmp
gfx/env/dfcliffrt.tga
gfx/env/dfcliffup.bmp
gfx/env/dfcliffup.tga
halflife.wad
lcd_display.wad
liquids.wad
maps/polar_rescue.cfg
maps/polar_rescue.gmr
maps/polar_rescue.gsr
maps/polar_rescue_materials.txt
maps/polar_rescue_motd.txt
maps/polar_rescue_skl.cfg
models/adamr/backpack_sven.mdl
models/adamr/ceiling_lamp.mdl
models/adamr/key.mdl
models/adamr/keycard_l1.mdl
models/adamr/keycard_l2.mdl
models/adamr/keycard_l3.mdl
models/adamr/toolbox.mdl
models/adamr/weapons/gold357/p_gold357.mdl
models/adamr/weapons/gold357/v_gold357_op4.mdl
models/adamr/weapons/gold357/w_gold357.mdl
models/blkop_apache.mdl
models/ginsmodels/gins_butcher.mdl
models/ginsmodels/gins_deskchair.mdl
models/ginsmodels/gins_mug.mdl
models/ginsmodels/gins_paring.mdl
models/ginsmodels/gins_pot.mdl
models/ginsmodels/gins_pot_lid.mdl
models/ginsmodels/gins_pot_nolid.mdl
models/ginsmodels/gins_substation.mdl
models/ginsmodels/gins_trashcan.mdl
models/ginsmodels/lag_radio.mdl
models/greysnake/hgrunt_medic.mdl
models/greysnake/hgrunt_opfor.mdl
models/greysnake/massn.mdl
models/hezus/mt32.mdl
models/nuke_button.mdl
models/nuke_case.mdl
models/nuke_timer.mdl
models/revil/Furnature/sink.mdl
models/revil/Furnature/toilet.mdl
models/tfc/detpack.mdl
models/the303/domecam.mdl
nw.wad
scripts/maps/polar_rescue.as
sound/adamr/bigexplode.wav
sound/adamr/blipblipblip.wav
sound/adamr/bubbles1.ogg
sound/adamr/electricbuzz.wav
sound/adamr/hgrunt/call_backup.wav
sound/adamr/lava.wav
sound/adamr/music/lotus-tuc-fmopl-cd1.ogg
sound/adamr/music/lotus-tuc-fmopl-cd2.ogg
sound/adamr/music/lotus-tuc-fmopl-cd3.ogg
sound/adamr/music/lotus-tuc-fmopl-cd4.ogg
sound/adamr/music/lotus-tuc-fmopl-cd5.ogg
sound/adamr/music/lotus-tuc-fmopl-cd6.ogg
sound/adamr/music/lotus-tuc-mt32-cd1.ogg
sound/adamr/music/lotus-tuc-mt32-cd2.ogg
sound/adamr/music/lotus-tuc-mt32-cd3.ogg
sound/adamr/music/lotus-tuc-mt32-cd4.ogg
sound/adamr/music/lotus-tuc-mt32-cd5.ogg
sound/adamr/music/lotus-tuc-mt32-cd6.ogg
sound/adamr/polar_rescue/3_minutes_remaining.wav
sound/adamr/polar_rescue/5_minutes_remaining.wav
sound/adamr/polar_rescue/10_minutes_remaining.wav
sound/adamr/polar_rescue/15_minutes_remaining.wav
sound/adamr/polar_rescue/20_minutes_remaining.wav
sound/adamr/polar_rescue/60_seconds_remaining.wav
sound/adamr/polar_rescue/missileroom_door_first_speech.wav
sound/adamr/polar_rescue/vault_door_first_speech.wav
sound/ambience/aliencave1.wav
sound/ambience/bigrumble.wav
sound/ambience/breather.wav
sound/ambience/burning1.wav
sound/ambience/burning2.wav
sound/ambience/computalk1.wav
sound/ambience/crtnoise.wav
sound/ambience/drips.wav
sound/ambience/dronemachine2.wav
sound/ambience/electrical_hum1.wav
sound/ambience/electrical_hum2.wav
sound/ambience/industrial1.wav
sound/ambience/industrial2.wav
sound/ambience/industrial4.wav
sound/ambience/mechwhine.wav
sound/ambience/pumper.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocket_groan4.wav
sound/ambience/rocket_steam1.wav
sound/ambience/rotormachine.wav
sound/ambience/signalgear1.wav
sound/ambience/steamjet1.wav
sound/ambience/water1.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall3.wav
sound/ambience/waterrun.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sound/apache/ap_rotor4.wav
sound/buttons/bell1.wav
sound/buttons/blip2.wav
sound/buttons/button1.wav
sound/buttons/lever4.wav
sound/buttons/lever5.wav
sound/buttons/spark5.wav
sound/debris/bustflesh1.wav
sound/extended/papers.wav
sound/fans/fan1.wav
sound/misc/r_tele3.wav
sound/plats/bigmove2.wav
sound/plats/bigstop1.wav
sound/stadium4/powerslam.wav
sound/vox/bloop.wav
sound/vox/dadeda.wav
sound/vox/deeoo.wav
sound/vox/doop.wav
sound/weapons/mine_charge.wav
sound/weapons/mine_deploy.wav
sprites/adamr/adambean.spr
sprites/adamr/diff.spr
sprites/adamr/diff_easy.spr
sprites/adamr/diff_extreme.spr
sprites/adamr/diff_hard.spr
sprites/adamr/diff_normal.spr
sprites/adamr/map_polarrescue.spr
sprites/adamr/pointers/pointer-blast.spr
sprites/adamr/pointers/pointer-collect.spr
sprites/adamr/pointers/pointer-destroy.spr
sprites/adamr/pointers/pointer-kill.spr
sprites/adamr/pointers/pointer-objective.spr
sprites/adamr/pointers/pointer-protect.spr
sprites/adamr/pointers/pointer-reach.spr
sprites/adamr/pointers/pointer-use.spr
sprites/billow_02.spr
sprites/c-tele1.spr
sprites/flare6.spr
sprites/glow03.spr
sprites/laserbeam.spr
sprites/lighting/glow.spr
sprites/lighting/glow_small.spr
sprites/lighting/glow_wide.spr
sprites/lighting/glow_wider.spr
sprites/xsmoke1.spr
sprites/xssmke1.spr
submerged.wad
submerged_addons.wad
xeno.wad
