// Created with resguy v6 (November 2017)
// https://github.com/wootguy/resguy

gfx/env/greenplanets_bk.tga
gfx/env/greenplanets_dn.tga
gfx/env/greenplanets_ft.tga
gfx/env/greenplanets_lf.tga
gfx/env/greenplanets_rt.tga
gfx/env/greenplanets_up.tga
maps/pvp_zombie_battleground.res
maps/pvp_zombie_battleground_motd.txt
sound/twzombie/aliencave1.wav
sound/twzombie/am_aliensm.wav
sound/twzombie/combine.wav
sound/twzombie/combine_touch.wav
sound/twzombie/countdown.wav
sound/twzombie/dude.wav
sound/twzombie/evil.wav
sound/twzombie/g7_goose3_down.wav
sound/twzombie/goodbye.wav
sound/twzombie/heyyeynoloop.wav
sound/twzombie/lavalaugh.wav
sound/twzombie/lifts.wav
sound/twzombie/machine_off.wav
sound/twzombie/machine_on.wav
sound/twzombie/nuke_explode.wav
sound/twzombie/scream03.wav
sound/twzombie/siren_wavering_nl.wav
sound/twzombie/teleporter_blast.wav
sound/twzombie/thriller.wav
sound/twzombie/tw_creepys.wav
sound/twzombie/tw_funeralmarchchopin.wav
sound/twzombie/tw_hauntedmansion.wav
sound/twzombie/tw_hauntedmansion2.wav
sound/twzombie/tw_scarymusic10.wav
sound/twzombie/tw_scarymusic12.wav
sound/twzombie/tw_scarymusic8.wav
sound/twzombie/tw_scarymusic9.wav
sound/twzombie/tw_spooky.wav
sound/twzombie/tw_zombie.wav
sound/twzombie/twitchbeam.wav
sound/twzombie/twitchloop.wav
sound/twzombie/ufo1.wav
sprites/twbattle/m_grflare3s.spr
