// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_hgrunt_m16.txt
events/muzzle_hgrunt_m40a1.txt
events/muzzle_hgrunt_mp5.txt
events/muzzle_hgrunt_sg.txt
events/muzzle_MP5.txt
events/muzzle_ns_hmg.txt
events/muzzle_ns_mg.txt
events/muzzle_ns_pistol.txt
events/muzzle_ns_sg.txt
events/muzzle_SG.txt
events/muzzle_spaw.txt
gfx/env/ragemap2025/ragedesert_bk.tga
gfx/env/ragemap2025/ragedesert_dn.tga
gfx/env/ragemap2025/ragedesert_ft.tga
gfx/env/ragemap2025/ragedesert_lf.tga
gfx/env/ragemap2025/ragedesert_rt.tga
gfx/env/ragemap2025/ragedesert_up.tga
halflife.wad
lcd_display.wad
maps/ragemap2025.res
models/hunger/hungerhound.mdl
models/hunger/hungerhoundt.mdl
models/ragemap2025/dust_particles.mdl
models/ragemap2025/fournines/agrunt_robo.mdl
models/ragemap2025/fournines/ax.mdl
models/ragemap2025/fournines/barchair.mdl
models/ragemap2025/fournines/barchair2.mdl
models/ragemap2025/fournines/beermug.mdl
models/ragemap2025/fournines/bgman.mdl
models/ragemap2025/fournines/bloodlurker.mdl
models/ragemap2025/fournines/bottle.mdl
models/ragemap2025/fournines/brepsi.mdl
models/ragemap2025/fournines/briefcase.mdl
models/ragemap2025/fournines/cashdesk.mdl
models/ragemap2025/fournines/datacube.mdl
models/ragemap2025/fournines/Four-Nines.mdl
models/ragemap2025/fournines/glass.mdl
models/ragemap2025/fournines/glass2.mdl
models/ragemap2025/fournines/helldrone.mdl
models/ragemap2025/fournines/ian.mdl
models/ragemap2025/fournines/jager.mdl
models/ragemap2025/fournines/jagerbox.mdl
models/ragemap2025/fournines/junkbox.mdl
models/ragemap2025/fournines/mrfatso.mdl
models/ragemap2025/fournines/NailForce.mdl
models/ragemap2025/fournines/NailForceTor.mdl
models/ragemap2025/fournines/netch.mdl
models/ragemap2025/fournines/p_fist.mdl
models/ragemap2025/fournines/p_leg.mdl
models/ragemap2025/fournines/p_nanosword.mdl
models/ragemap2025/fournines/p_shotgun.mdl
models/ragemap2025/fournines/peon.mdl
models/ragemap2025/fournines/pete.mdl
models/ragemap2025/fournines/robocontroller.mdl
models/ragemap2025/fournines/thug1.mdl
models/ragemap2025/fournines/v_fist.mdl
models/ragemap2025/fournines/v_leg.mdl
models/ragemap2025/fournines/v_nanosword.mdl
models/ragemap2025/fournines/v_shotgun.mdl
models/ragemap2025/fournines/valkyst.mdl
models/ragemap2025/fournines/van.mdl
models/ragemap2025/fournines/w_battery.mdl
models/ragemap2025/fournines/w_fist.mdl
models/ragemap2025/fournines/w_healthkit.mdl
models/ragemap2025/fournines/w_leg.mdl
models/ragemap2025/fournines/w_nanosword.mdl
models/ragemap2025/fournines/w_shotgun.mdl
models/ragemap2025/grunt/cart2.mdl
models/ragemap2025/grunt/crystal.mdl
models/ragemap2025/grunt/light.mdl
models/ragemap2025/grunt/monsters/fade.mdl
models/ragemap2025/grunt/monsters/skulk.mdl
models/ragemap2025/grunt/rock.mdl
models/ragemap2025/grunt/weapons/p_gr.mdl
models/ragemap2025/grunt/weapons/p_hg.mdl
models/ragemap2025/grunt/weapons/p_hmg.mdl
models/ragemap2025/grunt/weapons/p_mg.mdl
models/ragemap2025/grunt/weapons/p_sg.mdl
models/ragemap2025/grunt/weapons/shell.mdl
models/ragemap2025/grunt/weapons/shotshell.mdl
models/ragemap2025/grunt/weapons/v_gr.mdl
models/ragemap2025/grunt/weapons/v_hg.mdl
models/ragemap2025/grunt/weapons/v_hmg.mdl
models/ragemap2025/grunt/weapons/v_mg.mdl
models/ragemap2025/grunt/weapons/v_sg.mdl
models/ragemap2025/grunt/weapons/w_gr.mdl
models/ragemap2025/grunt/weapons/w_hg.mdl
models/ragemap2025/grunt/weapons/w_hmg.mdl
models/ragemap2025/grunt/weapons/w_mg.mdl
models/ragemap2025/grunt/weapons/w_sg.mdl
models/ragemap2025/hezus/models/discoball.mdl
models/ragemap2025/portal.mdl
models/ragemap2025/sand.mdl
models/ragemap2025/sand_bush.mdl
models/ragemap2025/sand_palm.mdl
models/rgruntf.mdl
nw.wad
nw_xeno.wad
ragemap2025.wad
scripts/maps/ragemap2025/credits.as
scripts/maps/ragemap2025/CustomHUD.as
scripts/maps/ragemap2025/fournines/weapon_dxnanosword.as
scripts/maps/ragemap2025/grunt.as
scripts/maps/ragemap2025/grunt/base.as
scripts/maps/ragemap2025/grunt/monster_fade.as
scripts/maps/ragemap2025/grunt/monster_skulk.as
scripts/maps/ragemap2025/grunt/proj_ns_grenade.as
scripts/maps/ragemap2025/grunt/vectorUtils.as
scripts/maps/ragemap2025/grunt/weapon_ns_grenade.as
scripts/maps/ragemap2025/grunt/weapon_ns_heavymachinegun.as
scripts/maps/ragemap2025/grunt/weapon_ns_machinegun.as
scripts/maps/ragemap2025/grunt/weapon_ns_pistol.as
scripts/maps/ragemap2025/grunt/weapon_ns_shotgun.as
scripts/maps/ragemap2025/ragemap2025.as
scripts/maps/ragemap2025/ragemap2025a.as
sound/agrunt/ag_alert1.wav
sound/agrunt/ag_alert3.wav
sound/ambience/distantmortar1.wav
sound/ambience/port_suckin1.wav
sound/ambience/weapons_unlocked.wav
sound/ambience/wind2.wav
sound/aslave/slv_word3.wav
sound/aslave/slv_word4.wav
sound/aslave/slv_word5.wav
sound/aslave/slv_word7.wav
sound/barney/ba_pain1.wav
sound/barney/ba_pain2.wav
sound/buttons/blip1.wav
sound/buttons/button10.wav
sound/buttons/latchunlocked2.wav
sound/common/npc_step1.wav
sound/common/npc_step2.wav
sound/common/npc_step3.wav
sound/common/npc_step4.wav
sound/common/null.wav
sound/debris/bustflesh1.wav
sound/hgrunt/gr_die1.wav
sound/hgrunt/gr_die2.wav
sound/hgrunt/gr_pain4.wav
sound/hl/weapons/357_cock1.wav
sound/hunger/hungerhound/he_alert1.wav
sound/hunger/hungerhound/he_alert2.wav
sound/hunger/hungerhound/he_alert3.wav
sound/hunger/hungerhound/he_attack1.wav
sound/hunger/hungerhound/he_attack2.wav
sound/hunger/hungerhound/he_hunt4.wav
sound/hunger/hungerhound/he_idle1.wav
sound/hunger/hungerhound/he_idle2.wav
sound/hunger/hungerhound/he_idle3.wav
sound/hunger/hungerhound/he_pain4.wav
sound/hunger/hungerhound/he_pain5.wav
sound/hunger/hungerhound/rex_bite1.wav
sound/hunger/hungerhound/rex_bite2.wav
sound/hunger/hungerhound/rex_bite3.wav
sound/hunger/thambs/wav.wav
sound/items/clipinsert1.wav
sound/items/cliprelease1.wav
sound/misc/dsbossit.wav
sound/misc/metal5.wav
sound/misc/party2.wav
sound/misc/secret.wav
sound/misc/spark1.wav
sound/misc/spark3.wav
sound/misc/spark4.wav
sound/ns/monsters/skulk/step1.wav
sound/ns/monsters/skulk/step2.wav
sound/ns/monsters/skulk/step4.wav
sound/ns/weapons/gr/grenade_draw.wav
sound/ns/weapons/gr/grenade_prime.wav
sound/ns/weapons/gr/grenade_throw.wav
sound/ns/weapons/hg/pistol_clipin.wav
sound/ns/weapons/hg/pistol_clipout.wav
sound/ns/weapons/hg/pistol_draw.wav
sound/ns/weapons/hg/pistol_slide_release.wav
sound/ns/weapons/hmg/hmg_clipin.wav
sound/ns/weapons/hmg/hmg_clipout.wav
sound/ns/weapons/hmg/hmg_close.wav
sound/ns/weapons/hmg/hmg_draw.wav
sound/ns/weapons/hmg/hmg_open.wav
sound/ns/weapons/hmg/hmg_slide.wav
sound/ns/weapons/mg/lmg_clipin.wav
sound/ns/weapons/mg/lmg_clipout.wav
sound/ns/weapons/mg/lmg_draw.wav
sound/ns/weapons/sg/shotgun_draw.wav
sound/ns/weapons/sg/shotgun_pump.wav
sound/ns/weapons/sg/shotgun_reload.wav
sound/null.wav
sound/otis/candy.wav
sound/otis/stupidmachines.wav
sound/pitdrone/pit_drone_attack_spike1.wav
sound/pitdrone/pit_drone_die1.wav
sound/pitdrone/pit_drone_die2.wav
sound/pitdrone/pit_drone_die3.wav
sound/pitdrone/pit_drone_eat.wav
sound/pitdrone/pit_drone_hunt3.wav
sound/pitdrone/pit_drone_melee_attack1.wav
sound/pitdrone/pit_drone_melee_attack2.wav
sound/ragemap2025/bonkturnip/basement_floor.ogg
sound/ragemap2025/demon_scream.ogg
sound/ragemap2025/fournines/36_cunt.wav
sound/ragemap2025/fournines/36_neverdrink.wav
sound/ragemap2025/fournines/36_wthismus.wav
sound/ragemap2025/fournines/anfight.ogg
sound/ragemap2025/fournines/anone.ogg
sound/ragemap2025/fournines/anthree.ogg
sound/ragemap2025/fournines/antwo.ogg
sound/ragemap2025/fournines/bosscomp.mp3
sound/ragemap2025/fournines/duke2bewild.ogg
sound/ragemap2025/fournines/LogNoteAdded.wav
sound/ragemap2025/fournines/npcs/agrunt_robo.txt
sound/ragemap2025/fournines/npcs/AssaultGunFire.wav
sound/ragemap2025/fournines/npcs/AssaultGunFire20mm.wav
sound/ragemap2025/fournines/npcs/AssaultGunReload.wav
sound/ragemap2025/fournines/npcs/AssaultGunReloadEnd.wav
sound/ragemap2025/fournines/npcs/death1.wav
sound/ragemap2025/fournines/npcs/death2.wav
sound/ragemap2025/fournines/npcs/death3.wav
sound/ragemap2025/fournines/npcs/deathc1.wav
sound/ragemap2025/fournines/npcs/deathc53.wav
sound/ragemap2025/fournines/npcs/fight1.wav
sound/ragemap2025/fournines/npcs/fight3.wav
sound/ragemap2025/fournines/npcs/fournines_massn.txt
sound/ragemap2025/fournines/npcs/fuckyou2.wav
sound/ragemap2025/fournines/npcs/hungerhound.txt
sound/ragemap2025/fournines/npcs/MaleDeath.wav
sound/ragemap2025/fournines/npcs/nailforcetor.txt
sound/ragemap2025/fournines/npcs/pain100_1.wav
sound/ragemap2025/fournines/npcs/pain25_1.wav
sound/ragemap2025/fournines/npcs/pain50_1.wav
sound/ragemap2025/fournines/npcs/pain75_1.wav
sound/ragemap2025/fournines/npcs/pieceshit.wav
sound/ragemap2025/fournines/npcs/ratfuck.wav
sound/ragemap2025/fournines/npcs/robocontroller.txt
sound/ragemap2025/fournines/npcs/sc55punch.wav
sound/ragemap2025/fournines/npcs/silence_hgrunt.txt
sound/ragemap2025/fournines/npcs/silence_otis.txt
sound/ragemap2025/fournines/npcs/SniperFire.wav
sound/ragemap2025/fournines/npcs/thuggun.txt
sound/ragemap2025/fournines/npcs/thugmelee.txt
sound/ragemap2025/fournines/npcs/thugsilent.txt
sound/ragemap2025/fournines/power.mp3
sound/ragemap2025/fournines/rmw1.mp3
sound/ragemap2025/fournines/rmw2.mp3
sound/ragemap2025/fournines/rmw3.mp3
sound/ragemap2025/fournines/rmw4.mp3
sound/ragemap2025/fournines/valkyst_hangover.wav
sound/ragemap2025/fournines/valkyst_lazyauthor.wav
sound/ragemap2025/fournines/w1comp.mp3
sound/ragemap2025/fournines/w2comp.mp3
sound/ragemap2025/fournines/w3comp.mp3
sound/ragemap2025/fournines/w4comp.mp3
sound/ragemap2025/fournines/weapons/nanosword_draw.wav
sound/ragemap2025/fournines/weapons/nanosword_hitwall.wav
sound/ragemap2025/fournines/weapons/nanosword_impact.wav
sound/ragemap2025/fournines/weapons/nanosword_swing.wav
sound/ragemap2025/grunt/ambience/bastturbine.ogg
sound/ragemap2025/grunt/ambience/blop.ogg
sound/ragemap2025/grunt/ambience/brief1.ogg
sound/ragemap2025/grunt/ambience/brief2.ogg
sound/ragemap2025/grunt/ambience/brief3.ogg
sound/ragemap2025/grunt/ambience/brief4.ogg
sound/ragemap2025/grunt/ambience/brief5.ogg
sound/ragemap2025/grunt/ambience/brief6.ogg
sound/ragemap2025/grunt/ambience/brief7.ogg
sound/ragemap2025/grunt/ambience/controlroom.ogg
sound/ragemap2025/grunt/ambience/doormove.wav
sound/ragemap2025/grunt/ambience/doorstop.wav
sound/ragemap2025/grunt/ambience/hive_ambient.ogg
sound/ragemap2025/grunt/ambience/processing.ogg
sound/ragemap2025/grunt/drilling.ogg
sound/ragemap2025/grunt/monsters/asay31.wav
sound/ragemap2025/grunt/monsters/fade/blinksuccess.wav
sound/ragemap2025/grunt/monsters/fade/claws1.wav
sound/ragemap2025/grunt/monsters/fade/claws2.wav
sound/ragemap2025/grunt/monsters/fade/claws3.wav
sound/ragemap2025/grunt/monsters/fade/role6_die1.wav
sound/ragemap2025/grunt/monsters/fade/role6_idle1.wav
sound/ragemap2025/grunt/monsters/fade/role6_move1.wav
sound/ragemap2025/grunt/monsters/fade/role6_pain1.wav
sound/ragemap2025/grunt/monsters/fade/role6_wound1.wav
sound/ragemap2025/grunt/monsters/skulk/bite.wav
sound/ragemap2025/grunt/monsters/skulk/bite2.wav
sound/ragemap2025/grunt/monsters/skulk/leap1.wav
sound/ragemap2025/grunt/monsters/skulk/leaphit1.wav
sound/ragemap2025/grunt/monsters/skulk/role4_die1.wav
sound/ragemap2025/grunt/monsters/skulk/role4_idle1.wav
sound/ragemap2025/grunt/monsters/skulk/role4_pain1.wav
sound/ragemap2025/grunt/monsters/skulk/role4_wound1.wav
sound/ragemap2025/grunt/monsters/skulk/role4_wound2.wav
sound/ragemap2025/grunt/monsters/skulk/role5_move1.wav
sound/ragemap2025/grunt/weapons/explode1.wav
sound/ragemap2025/grunt/weapons/explode2.wav
sound/ragemap2025/grunt/weapons/explode3.wav
sound/ragemap2025/grunt/weapons/gr/grenade_draw.wav
sound/ragemap2025/grunt/weapons/gr/grenade_hit1.wav
sound/ragemap2025/grunt/weapons/gr/grenade_hit2.wav
sound/ragemap2025/grunt/weapons/gr/grenade_hit3.wav
sound/ragemap2025/grunt/weapons/gr/grenade_prime.wav
sound/ragemap2025/grunt/weapons/gr/grenade_throw.wav
sound/ragemap2025/grunt/weapons/hg/hg-1.wav
sound/ragemap2025/grunt/weapons/hg/pistol_clipin.wav
sound/ragemap2025/grunt/weapons/hg/pistol_clipout.wav
sound/ragemap2025/grunt/weapons/hg/pistol_draw.wav
sound/ragemap2025/grunt/weapons/hg/pistol_slide_release.wav
sound/ragemap2025/grunt/weapons/hmg/hmg-1.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_clipin.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_clipout.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_close.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_draw.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_open.wav
sound/ragemap2025/grunt/weapons/hmg/hmg_slide.wav
sound/ragemap2025/grunt/weapons/mg/lmg_clipin.wav
sound/ragemap2025/grunt/weapons/mg/lmg_clipout.wav
sound/ragemap2025/grunt/weapons/mg/lmg_draw.wav
sound/ragemap2025/grunt/weapons/mg/mg-1.wav
sound/ragemap2025/grunt/weapons/sg/sg-1.wav
sound/ragemap2025/grunt/weapons/sg/sg-cock.wav
sound/ragemap2025/grunt/weapons/sg/shotgun_draw.wav
sound/ragemap2025/grunt/weapons/sg/shotgun_pump.wav
sound/ragemap2025/grunt/weapons/sg/shotgun_reload.wav
sound/ragemap2025/grunt/weapons/sg/shotgun_stock_release.wav
sound/ragemap2025/hezus/disco_funky.mp3
sound/ragemap2025/hezus/disco_house.mp3
sound/ragemap2025/hezus/disco_paradise.mp3
sound/ragemap2025/hezus/disco_party.mp3
sound/ragemap2025/outro.ogg
sound/ragemap2025/quake.ogg
sound/ragemap2025/ragemap2025_materials.txt
sound/ragemap2025/ragemap2025_sentences.txt
sound/ragemap2025/sand_fall.ogg
sound/tfc/ambience/goal_1.wav
sound/tfc/weapons/airgun_1.wav
sound/tfc/weapons/spike1.wav
sound/tfc/weapons/spike2.wav
sound/turret/tu_active2.wav
sound/turret/tu_alert.wav
sound/turret/tu_deploy.wav
sound/turret/tu_die.wav
sound/turret/tu_die2.wav
sound/turret/tu_die3.wav
sound/turret/tu_retract.wav
sound/turret/tu_search.wav
sound/vox/_comma.wav
sound/vox/access.wav
sound/vox/acquired.wav
sound/vox/bizwarn.wav
sound/vox/bloop.wav
sound/vox/buzwarn.wav
sound/vox/detonation.wav
sound/vox/engage.wav
sound/vox/granted.wav
sound/vox/in.wav
sound/vox/seconds.wav
sound/vox/target.wav
sound/vox/thirty.wav
sound/weapons/boltdown.wav
sound/weapons/boltpull.wav
sound/weapons/bullet_hit1.wav
sound/weapons/bullet_hit2.wav
sound/weapons/electro4.wav
sound/weapons/electro5.wav
sound/weapons/g_bounce5.wav
sound/weapons/gren_cock1.wav
sound/weapons/m3_insertshell.wav
sound/weapons/m3_pump.wav
sound/weapons/reload1.wav
sound/weapons/reload3.wav
sound/weapons/scock1.wav
sound/weapons/uzi/reload1.wav
sound/weapons/uzi/reload2.wav
sound/weapons/uzi/shoot1.wav
sound/weapons/uzi/shoot2.wav
sound/weapons/uzi/shoot3.wav
sprites/adamr/pointers/pointer-collect.spr
sprites/bluemuzzle.spr
sprites/eexplo.spr
sprites/fexplo.spr
sprites/flare1.spr
sprites/glow01.spr
sprites/glow02.spr
sprites/glow03.spr
sprites/glow04.spr
sprites/laserbeam.spr
sprites/MP5Flash.spr
sprites/muzzleflash3.spr
sprites/ns/muzzleflash1.spr
sprites/Puff1.spr
sprites/ragemap2025/fournines/weapons/640hudnanosword.spr
sprites/ragemap2025/fournines/weapons/weapon_dxnanosword.txt
sprites/ragemap2025/grunt/640hud7.spr
sprites/ragemap2025/grunt/640mw1-s.spr
sprites/ragemap2025/grunt/640mw1.spr
sprites/ragemap2025/grunt/640mw2-s.spr
sprites/ragemap2025/grunt/640mw2.spr
sprites/ragemap2025/grunt/weapon_ns_grenade.txt
sprites/ragemap2025/grunt/weapon_ns_heavymachinegun.txt
sprites/ragemap2025/grunt/weapon_ns_machinegun.txt
sprites/ragemap2025/grunt/weapon_ns_pistol.txt
sprites/ragemap2025/grunt/weapon_ns_shotgun.txt
sprites/ragemap2025/grunt/xhairmw1.spr
sprites/ragemap2025/grunt/xhairmw5.spr
sprites/redflare1.spr
sprites/SAWFlash.spr
sprites/SGFlash.spr
sprites/spotlight02.spr
sprites/steam1.spr
sprites/WXplo1.spr
sprites/ragemap2025/channelicon_intro.spr
sprites/ragemap2025/channelicon_outro.spr
sprites/ragemap2023/tickets.spr
sprites/ragemap2025/channelicon_bonk.spr
sprites/ragemap2025/channelicon_fn.spr
sprites/ragemap2025/channelicon_grunt.spr
sprites/ragemap2025/channelicon_hezus.spr
sprites/ragemap2025/credits/credits_bonk.spr
sprites/ragemap2025/credits/credits_fn.spr
sprites/ragemap2025/credits/credits_grunt.spr
sprites/ragemap2025/credits/credits_hezus.spr
sprites/ragemap2025/credits/credits_thanks.spr