gfx/env/sc5xbk.tga
gfx/env/sc5xdn.tga
gfx/env/sc5xft.tga
gfx/env/sc5xlf.tga
gfx/env/sc5xrt.tga
gfx/env/sc5xup.tga
maps/sc5x_bonus.cfg
maps/sc5x_bonus_motd.txt
models/opfor/p_knife.mdl
models/opfor/v_knife.mdl
models/opfor/w_knife.mdl
models/player/massn_blue/massn_blue.bmp
models/player/massn_blue/massn_blue.mdl
models/player/maasn_red/maasn_red.bmp
models/player/maasn_red/maasn_red.mdl
models/sc5x_bonus/farmerdance.mdl
models/sc5x_bonus/farmerdance2.mdl
sound/sc5x_bonus/bartrack1a.ogg
sound/sc5x_bonus/classicradio.ogg
sound/sc5x_bonus/electrichum.ogg
sound/sc5x_bonus/farmerdance.ogg
sound/sc5x_bonus/sc5xharbour2.ogg
sprites/sc5x_bonus/captive_zone.spr
sprites/sc5x_bonus/loc_city.spr
sprites/sc5x_bonus/loc_docks.spr
