models/spaceviking/cbarney01.mdl
models/spaceviking/cbarney02.mdl
models/spaceviking/cbarney03.mdl
models/spaceviking/cbarney.mdl
models/spaceviking/cbarneyt.mdl
models/spaceviking/p_crowbar.mdl
models/spaceviking/robobug2.mdl
models/spaceviking/spirate.mdl
models/spaceviking/v_crowbar.mdl
models/spaceviking/w_crowbar.mdl
gfx/env/blood-sport256_bk.bmp
gfx/env/blood-sport256_bk.tga
gfx/env/blood-sport256_dn.bmp
gfx/env/blood-sport256_dn.tga
gfx/env/blood-sport256_ft.bmp
gfx/env/blood-sport256_ft.tga
gfx/env/blood-sport256_lf.bmp
gfx/env/blood-sport256_lf.tga
gfx/env/blood-sport256_rt.bmp
gfx/env/blood-sport256_rt.tga
gfx/env/blood-sport256_up.bmp
gfx/env/blood-sport256_up.tga
maps/sc_spaceviking2.cfg
maps/sc_spaceviking2.txt
maps/sc_spaceviking2_models.txt
maps/sc_spaceviking2_motd.txt