// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/ap_keycard.mdl
models/urbicide/bush_evergreen.mdl
models/urbicide/bush_fern_small.mdl
models/urbicide/bush_japan_bush01.mdl
models/urbicide/bush_japan_fern_01.mdl
models/urbicide/bush_shrubv01.mdl
models/urbicide/deadbody2.mdl
models/urbicide/deadbody4.mdl
models/urbicide/deadbody6.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/fork1.mdl
models/urbicide/hgrunt.mdl
models/urbicide/rock_japan_rocks2.mdl
models/urbicide/s_mallet.mdl
models/urbicide/sci_deadbody1.mdl
models/urbicide/tree_greyv1.mdl
models/urbicide/tree_japan_maple_orange.mdl
models/urbicide/tree_japan_maple_red.mdl
models/urbicide/tree_japan_round.mdl
models/urbicide/tree_noleaves.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
poke646.wad
sound/urbicide/ambience/exp2.wav
sound/urbicide/ambience/fire_alarm1.wav
sound/urbicide/ambience/fluorescent.wav
sound/urbicide/ambience/tunnel_amb.wav
sound/urbicide/ambience/water_flowing1.wav
sound/urbicide/music/half-life06.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
urbicide.wad
vendetta.wad
