// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/cc_footwear_12.mdl
models/urbicide/deadbody4.mdl
models/urbicide/deadbody5.mdl
models/urbicide/fem_deadbody1.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/forklift01.mdl
models/urbicide/hgrunt.mdl
models/urbicide/shampoo_bottle.mdl
models/urbicide/soap.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
models/urbicide/zps_radiator.mdl
poke646.wad
sound/urbicide/ambience/button5.wav
sound/urbicide/ambience/computalk2.wav
sound/urbicide/ambience/eating1.wav
sound/urbicide/ambience/exp3.wav
sound/urbicide/ambience/fan4_new.wav
sound/urbicide/ambience/flies.wav
sound/urbicide/ambience/fluorescent.wav
sound/urbicide/ambience/industrial4.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/toilet_flush1.wav
sound/urbicide/ambience/tunnel_amb.wav
sound/urbicide/ambience/water_drips2.wav
sound/urbicide/ambience/water_flowing1.wav
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
vendetta.wad
