// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/af_pallete_pushcart.mdl
models/urbicide/deadbody6.mdl
models/urbicide/deadbody7.mdl
models/urbicide/forklift01.mdl
models/urbicide/hgrunt.mdl
models/urbicide/hummer.mdl
models/urbicide/keydrop.mdl
models/urbicide/renaultrig.mdl
models/urbicide/s_truck2.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
poke646.wad
sound/urbicide/ambience/exp2.wav
sound/urbicide/ambience/exp3.wav
sound/urbicide/ambience/exp4.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/plane_crash1.wav
sound/urbicide/ambience/plane_fly1.wav
sound/urbicide/ambience/saw_fire1.wav
sound/urbicide/ambience/tank_fire1.wav
sound/urbicide/ambience/warthog.wav
sound/urbicide/ambience/wind2.wav
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
vendetta.wad
