// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/deadbody4.mdl
models/urbicide/hgrunt.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
poke646.wad
sound/urbicide/ambience/bhawk_move.wav
sound/urbicide/ambience/camp_water.wav
sound/urbicide/ambience/computalk2.wav
sound/urbicide/ambience/computalk4.wav
sound/urbicide/ambience/damage_guns_loop.wav
sound/urbicide/ambience/fan4_new.wav
sound/urbicide/ambience/flies.wav
sound/urbicide/ambience/industrial2.wav
sound/urbicide/ambience/industrial4.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/trailer_dripecho_loop.wav
sound/urbicide/ambience/tunnel_amb.wav
sound/urbicide/ambience/water_drips.wav
sound/urbicide/ambience/water_flowing1.wav
sound/urbicide/ambience/water_flowing3.wav
sound/urbicide/ambience/water_lap1.wav
sound/urbicide/ambience/waterrun.wav
sound/urbicide/music/half-life03.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
vendetta.wad
