// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/af_pallete_pushcart.mdl
models/urbicide/airconditioner.mdl
models/urbicide/andersen.mdl
models/urbicide/car_scrap.mdl
models/urbicide/car_scrapped.mdl
models/urbicide/cc_footwear_12.mdl
models/urbicide/cc_prcloth_01_a.mdl
models/urbicide/cod4_shipti.mdl
models/urbicide/coffee_props-sugar.mdl
models/urbicide/computer_mouse01.mdl
models/urbicide/deadbody1.mdl
models/urbicide/deadbody2.mdl
models/urbicide/deadbody3.mdl
models/urbicide/deadbody4.mdl
models/urbicide/deadbody7.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/flatbeadtrailer.mdl
models/urbicide/forklift.mdl
models/urbicide/forklift01.mdl
models/urbicide/hbm_hammer.mdl
models/urbicide/hbm_screwdriver.mdl
models/urbicide/hgrunt.mdl
models/urbicide/hummer.mdl
models/urbicide/kosobar.mdl
models/urbicide/phone_pay-us.mdl
models/urbicide/s_truck2.mdl
models/urbicide/semi_trailer.mdl
models/urbicide/tool_box.mdl
models/urbicide/trash.mdl
models/urbicide/trash_02.mdl
models/urbicide/trash_trashbag.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
models/urbicide/zps_radiator.mdl
poke646.wad
sound/urbicide/ambience/airstrike1.wav
sound/urbicide/ambience/amc_loop2.wav
sound/urbicide/ambience/exp2.wav
sound/urbicide/ambience/flies.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/james1.wav
sound/urbicide/ambience/james2.wav
sound/urbicide/ambience/james3.wav
sound/urbicide/ambience/james4.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/rusty1.wav
sound/urbicide/ambience/rusty2.wav
sound/urbicide/ambience/rusty3.wav
sound/urbicide/ambience/rusty4.wav
sound/urbicide/ambience/urbicide_amb1.wav
sound/urbicide/ambience/water_gentle1.wav
sound/urbicide/ambience/water_lap1.wav
sound/urbicide/ambience/water_loop1.wav
sound/urbicide/ambience/wind2.wav
sound/urbicide/music/half-life01.mp3
sound/urbicide/music/half-life02.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
urbicide.wad
vendetta.wad
