// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/af_pallete_pushcart.mdl
models/urbicide/computer_mouse01.mdl
models/urbicide/deadbody6.mdl
models/urbicide/deadbody7.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/fork1.mdl
models/urbicide/hgrunt.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
poke646.wad
sound/urbicide/ambience/bell1.wav
sound/urbicide/ambience/blackhawk_flyoff.wav
sound/urbicide/ambience/building_pipedream.wav
sound/urbicide/ambience/camp_water.wav
sound/urbicide/ambience/computalk2.wav
sound/urbicide/ambience/damage_guns_loop.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/law_travel.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/platmove1.wav
sound/urbicide/ambience/water_flowing3.wav
sound/urbicide/ambience/water_gentle1.wav
sound/urbicide/music/half-life04.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
urbicide.wad
vendetta.wad
