// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/aa_czervanian_lowclass_car2_sm.mdl
models/urbicide/aa_czervanian_lowclass_car_sm.mdl
models/urbicide/bush_fern_small.mdl
models/urbicide/bush_japan_bush01.mdl
models/urbicide/car_scrap.mdl
models/urbicide/cc_phone.mdl
models/urbicide/computer_mouse01.mdl
models/urbicide/deadbody1.mdl
models/urbicide/deadbody3.mdl
models/urbicide/deadbody5.mdl
models/urbicide/fem_deadbody1.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/hbm_hammer.mdl
models/urbicide/hgrunt.mdl
models/urbicide/hummer.mdl
models/urbicide/phone_booth.mdl
models/urbicide/s_mallet.mdl
models/urbicide/s_truck2.mdl
models/urbicide/sci_deadbody1.mdl
models/urbicide/sci_deadbody2.mdl
models/urbicide/sci_deadbody3.mdl
models/urbicide/tree_brownv01.mdl
models/urbicide/tree_japan_round.mdl
models/urbicide/tree_noleaves.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/zombie.mdl
models/urbicide/zps_radiator.mdl
poke646.wad
sound/urbicide/ambience/bell1.wav
sound/urbicide/ambience/button5.wav
sound/urbicide/ambience/damage_boom_loop.wav
sound/urbicide/ambience/eating1.wav
sound/urbicide/ambience/fluorescent.wav
sound/urbicide/ambience/plat_stop1.wav
sound/urbicide/ambience/platmove1.wav
sound/urbicide/ambience/warthog.wav
sound/urbicide/music/half-life05.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
urbicide.wad
vendetta.wad
