// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/urbicide/aa_condiments01_gl_smesh.mdl
models/urbicide/aa_stack_plate02_gl_smesh.mdl
models/urbicide/airconditioner.mdl
models/urbicide/bananna_bunch.mdl
models/urbicide/buzzer_beer.mdl
models/urbicide/car_scrap.mdl
models/urbicide/car_scrapped.mdl
models/urbicide/cc_footwear_07.mdl
models/urbicide/cc_footwear_09.mdl
models/urbicide/cc_footwear_12.mdl
models/urbicide/cc_phone.mdl
models/urbicide/cc_prcloth_01_a.mdl
models/urbicide/cc_prcloth_01_b.mdl
models/urbicide/cc_prcloth_01_c.mdl
models/urbicide/cc_prcloth_02_c.mdl
models/urbicide/coffee_props-sugar.mdl
models/urbicide/computer_mouse01.mdl
models/urbicide/deadbody1.mdl
models/urbicide/deadbody2.mdl
models/urbicide/deadbody3.mdl
models/urbicide/dnc_truck1.mdl
models/urbicide/fem_deadbody2.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/hgrunt.mdl
models/urbicide/hummer.mdl
models/urbicide/jrx_foodwrap1.mdl
models/urbicide/jrx_jeans.mdl
models/urbicide/kosobar.mdl
models/urbicide/me3_paper_pile04.mdl
models/urbicide/mex_veh_ikarus_br_low.mdl
models/urbicide/pot-2.mdl
models/urbicide/rebecca2.mdl
models/urbicide/rug_oriental-large.mdl
models/urbicide/rug_oriental-large3.mdl
models/urbicide/s_frypan.mdl
models/urbicide/s_knife.mdl
models/urbicide/s_melon.mdl
models/urbicide/shampoo_bottle.mdl
models/urbicide/soap.mdl
models/urbicide/trash.mdl
models/urbicide/trash_02.mdl
models/urbicide/trash_trashbag.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/vts_kitchen_tushenka.mdl
models/urbicide/w_cleaver.mdl
models/urbicide/w_kitchenknife.mdl
models/urbicide/zombie.mdl
models/urbicide/zps_radiator.mdl
poke646.wad
sound/urbicide/ambience/arcticwind_gust4.wav
sound/urbicide/ambience/biolab_windoutside_loop.wav
sound/urbicide/ambience/button5.wav
sound/urbicide/ambience/cart1.wav
sound/urbicide/ambience/damage_boom_loop.wav
sound/urbicide/ambience/knocking1.wav
sound/urbicide/ambience/rebecca_scream1.wav
sound/urbicide/ambience/refrigerator_loop.wav
sound/urbicide/ambience/tv_chatter1.wav
sound/urbicide/music/half-life07.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/pl_gun3.wav
sprites/hl_weapons/weapon_hlpython.txt
stlouis.wad
sunnywoods.wad
urbicide.wad
vendetta.wad
